apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
  - name: auth-secret
    envs:
      - env.properties
  - name: db-secret
    envs:
      - ../db.env
  - name: minio-secret
    envs:
      - minio.env

generatorOptions:
  disableNameSuffixHash: true

resources:
  - "../../../base/auth"
