apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
type: Opaque
data:
  MINIO_ENDPOINT: Q01TVFQuY29tcGF0Lm9iamVjdHN0b3JhZ2UudXMtYXNoci1iYXVybC0xLm9yYWNsZWNsb3VkLmNvbQ==
  MINIO_PORT: ""
  MINIO_SSL: dHJ1ZQ==
  MINIO_ACCESS_KEY: MDM5YzMwMGE0MTIzYjhiNzMxZDYxMmJhYTIxN2Y3MjZlOTYwNDVhOA==
  MINIO_SECRET_KEY: IDMzRENYdVE3QU5JcFJBVzFYRERKS0FDakhrUXQxR2FkeVZZVkhkMkI1UTQ9Cg==
  MINIO_BUCKET_NAME: Q01TVFc=
  MINIO_URL_EXPIRY: MjQ=
  MINIO_REGION: ImFzaGJ1cm4i