apiVersion: v1
kind: Secret
metadata:
  name: organization-secret
type: Opaque
data:
  APP_DEBUG: dHJ1ZQ==
  APP_PORT: MzAwMA==
  DB_HOST: MTAuMjUwLjMuMTg3
  DB_PORT: MzMwNg==
  DB_USERNAME: U1lTVEVN
  DB_PASSWORD: VU00U1NMYXgyMDIwLTIj
  DB_NAME: bWV0YQ==
  META_AUTH_URL: aHR0cHM6Ly9tcy1hdXRoLmZ1c2lvbi5jb20uYXI=
  META_PROJECT_URL: aHR0cHM6Ly9tcy1wcm9qZWN0cy5mdXNpb24uY29tLmFy
  META_PROCESS_URL: aHR0cHM6Ly9tcy1wcm9jZXNzLmZ1c2lvbi5jb20uYXI=
  OAUTH_CLIENT_ID: bTNUNGYwcjBtM1I1LXFh
  OAUTH_CLIENT_SECRET: UUJpajJWUVhUZCRkNHJGcnA=
