apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  APP_DEBUG: dHJ1ZQ==
  APP_PORT: MzAwMA==
  META_AUTH_URL: aHR0cHM6Ly9tcy1hdXRoLmZ1c2lvbi5jb20uYXI= 
  META_PROJECT_URL: aHR0cHM6Ly9tcy1wcm9qZWN0cy5mdXNpb24uY29tLmFy 
  META_ORGANIZATION_URL: aHR0cHM6Ly9tcy1vcmdhbml6YXRpb24uZnVzaW9uLmNvbS5hcg==
  META_SURVEY_URL: aHR0cHM6Ly9tcy1zdXJ2ZXlzLmZ1c2lvbi5jb20uYXI= 
  FILE_STORAGE_TYPES: aW1hZ2UvanBlZyxpbWFnZS9wbmcsdGV4dC9jc3Z5LmNzdiwicmVxdWVzdGluZy9kZXBsb3ltZW50LnNwZWVkb3Quc3BsYXNoZWQubWxlY3RhdGxpbmcuc2hlZXQuaW5kZXhwb3J0cy5zcGVjaWZpZWxtdC5zaGVldA== 
  FILE_MAX_SIZE: MTAgICAgICAgICAgICAg 
  OAUTH_CLIENT_ID: bTNUNGYwcjBtM1I1LXFh
  OAUTH_CLIENT_SECRET: UUJpajJWUVhUZCRkNHJGcnA=
  DB_HOST: bXlzcWw=
  DB_NAME: bWV0YQ==
  DB_PASSWORD: bWV0YQ==
  DB_PORT: MzMwNg==
  DB_USERNAME: bWV0YQ==
  MINIO_ENDPOINT: Q01TVFQuY29tcGF0Lm9iamVjdHN0b3JhZ2UudXMtYXNoci1iYXVybC0xLm9yYWNsZWNsb3VkLmNvbQ==
  MINIO_PORT: ""
  MINIO_SSL: dHJ1ZQ==
  MINIO_ACCESS_KEY: MDM5YzMwMGE0MTIzYjhiNzMxZDYxMmJhYTIxN2Y3MjZlOTYwNDVhOA==
  MINIO_SECRET_KEY: IDMzRENYdVE3QU5JcFJBVzFYRERKS0FDakhrUXQxR2FkeVZZVkhkMkI1UTQ9Cg==
  MINIO_BUCKET_NAME: Q01TVFc=
  MINIO_URL_EXPIRY: MjQ=
  MINIO_REGION: ImFzaGJ1cm4i