apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-process
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-process
  template:
    metadata:
      labels:
        app: ms-process
    spec:
      containers:
        - name: ms-process
          envFrom:
            - secretRef:
                name: process-secret
            - secretRef:
                name: db-secret
          image: jmartinezblanco/meta-ms-process
          ports:
            - containerPort: 3000
              protocol: TCP

