---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: file-secret
spec:
  encryptedData:
    FILE_MAX_SIZE: AgB6LbDTflXMjLEALIcOCJ/FEkFaU+fqP9tuqg4EOFz7CltB9pTVyifVvccYNHgtvP3Vg81DWKP//ynUxS+NUgIWLXMz3Y78xrc68lHwDNc3O7k2Qpji4VqRXilqtI4MUaJhfc2dNirgsNgyPMuEzil82uTlSi0c7lrSbftydsisSkKWwRtbvrDsEWev6RZHEf1dky7oXoWmX+P9v6B++1UrYTovVKgceMTQlceNHsJnuJhXWg6siYIjPv9tvza1jR3e6FbFfORfHEjw2CNUYtFiEc7fUeHHDiZzGUqcsW9gHjeV2Lw8TN1296VpcdgNVQv4HyvH7K20sqYV+7NYzPQRHSz5cDh23ToL528VU9ncCwoWKmDQd5Fp0ayZIpd2W6RCoIDy9MRuxaOByOTU9gU8wnAxb2U2bk1W/KozBBwi7nNocvbvtG1OVl09CKJ6KvwcmpJShuvHXvfCwtqRnGMSsx4dPOMVbcSzk78E6H+ipt5kiBw29amjwRx6nL8grdwJEJzBkDREaq3z+u+DpkxGE0M/K7vK0dTBJZwedrpb6mAu6gbR/HeeSXE0ddGzjCiTQYqpP3xf2vgCoS2z0PPT+TEk+TY6szz4KmzL2v92Am+Nc/nUFctXwP7Rh2m/lbo+koRmsCO/x2K5gDo3hcTcwg95xo2zE+NE6VCf2Bxh+yOUkJ3EMh5qxGtPOWK6D5BEw3G7b5yCJvKq6+aoYes=
    FILE_STORAGE_TYPES: AgCpU392I1WsNNF1r4NdqgdjW/mnfbhH2d2hBTDumVkziIjrxBNowBE85VdBYWc8XsA9Io63jO7jsdypU9NI+0woRMyLbNcOfOXF6jLs2Y4XrBYhFkvysYU9bfW2xKJZJaUCoCovTmEeAOGFhbVQD+i2/BpxVtZgmjprzXMoIbb1xNWbs7JeeeZwfQ3VM4y0snVZF46kRFwR4jA6/sUw/g3sDyjDAyhyNm7OJm803ZqQlBexGE+28av8ZBbjjayN7XPAkcuFjiQvBgINBt3hDo1FxjsUYprfVYOEVFy2e1Crt2OwCb1rgvN2vYvjTufLks/w8cCkvFP0zMUzkZa2Mk2FKZGYCjfjoOxQ2zbRDvw/Bge7rMFX4tNegK+8CGMcRnJnw4vIWGQIlOqFcmIGXmj+VSJEAqXVG3OPTs0olntjUUvTInhVFBsQaKz780O11ZOU76Hqs2g5h9vByuugZcUxkbCQo2J0SP3MfQEHETjAzaCP7wi60Qn4JMzyl3g/9xNLAfawJCdfPMdaoVTRiXwUkKkJDvVLMHmkh7asd1U2dX4bFM+8I8WJq4Ee9p9zMBRfQwXxPppb2s357X0MYaIK9k44eKT5fcBhZp8/6IImVTdoktugBbsF5lIxrO/dAOQSnWZ7uun+sYuCnJlMUdNTD4MBAnvEUFViAtOwEbAuZ5L+111EKC5Z+g3Nk5hCmh5CIcUBuubxtV8VsST/GZcsKHdblQHeix7Fg2mgKzU4feOGOcOBv9Gpl5V+ZsTn32JxcWJ653f9HvhC3iRWWHHnb6FzcXSIg9TvuUAhqp5BzKss3dDs27fE78PkDqX3UeuiIoY9gyLE34o8P/tpkKQjEijh0a6RSjpxsOlVWwpMgmSWMOCloJrbv/Qs0hPtUwzBzo+KJEoZt1nPpLTnRGI4A7UP8v4djEbTwwYcHYRZ9VpuuPs/IEt1nCyGPjhesh6H9Cjh4PmnS1Hi/+KfMh9eocxNYPdNGuZmapX4gsuz5fFnpuVVpzL/c8zxo4/jvLNC6F3jWu4f3YLSHAvHiE3W0bKgfIciJbdZPIDgGJKLxSNz7GNZFO2R+643TWaSOJmh05pilJvPSBRR504CKKPtn6AYy+J1EiM=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: file-secret
    type: Opaque
