apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-surveys-cron
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-surveys-cron
  template:
    metadata:
      labels:
        app: ms-surveys-cron
    spec:
      imagePullSecrets:
      - name: oci-registry
      containers:
        - name: ms-surveys-cron
          envFrom:
            - secretRef:
                name: surveys-cron-secret
            - secretRef:
                name: db-secret
          image: iad.ocir.io/idwwmbyiyhww/meta-ms-surveys:latest
          ports:
            - containerPort: 3000
              protocol: TCP
